ke_opti_sche: {
  optimizer: {
    type: AdamW,
    kwargs: {
      lr: 0.0005,
      weight_decay: 0.0005
    }},
  scheduler: {
    type: LambdaLR,
    kwargs: {
      decay_step: 21,
      lr_decay: 0.76,
      lowest_decay: 0.02  # min lr = lowest_decay * lr
    }},
  bnmscheduler: {
    type: Lambda,
    kwargs: {
      decay_step: 21,
      bn_decay: 0.5,
      bn_momentum: 0.9,
      lowest_decay: 0.01
    }}
}

ve_opti_sche: {
  optimizer: {
    type: AdamW,
    kwargs: {
      lr: 0.0005,
      weight_decay: 0.0005
    }},
  scheduler: {
    type: LambdaLR,
    kwargs: {
      decay_step: 21,
      lr_decay: 0.76,
      lowest_decay: 0.02  # min lr = lowest_decay * lr
    }},
  bnmscheduler: {
    type: Lambda,
    kwargs: {
      decay_step: 21,
      bn_decay: 0.5,
      bn_momentum: 0.9,
      lowest_decay: 0.01
    }}
}

key_encoder : {
  NAME: PCT,
  in_chans: 3,
  embed_dim: 384,
  depth:[6,8],
  num_heads: 6,
  mlp_ratio: 2.,
  qkv_bias: False,
  qk_scale: None,
  drop_rate: 0.,
  attn_drop_rate: 0.,
  knn_layer: 1,
  num_group: 32,
  calc_dim: 1411
}

value_encoder : {
  NAME: PCT,
  in_chans: 3,
  embed_dim: 384,
  depth:[6,8],
  num_heads: 6,
  mlp_ratio: 2.,
  qkv_bias: False,
  qk_scale: None,
  drop_rate: 0.,
  attn_drop_rate: 0.,
  knn_layer: 1,
  num_group: 128,
  calc_dim: 1411,
}

decoder : {
  NAME: foldnet,
  in_channel: 384,
  step: 8,
  hidden_dim: 256
}